version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@cucumber/cucumber"
    versions:
    - 7.2.1
  - dependency-name: "@cucumber/gherkin"
    versions:
    - 18.1.1
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.25.0
  - dependency-name: strip-ansi
    versions:
    - 7.0.0
  - dependency-name: devtools-protocol
    versions:
    - 0.0.868034
  - dependency-name: aws-sdk
    versions:
    - 2.858.0
    - 2.868.0
  - dependency-name: lighthouse
    versions:
    - 7.3.0
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: lerna
    versions:
    - 4.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
  - dependency-name: "@types/cheerio"
    versions:
    - 0.22.27
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.3
  - dependency-name: puppeteer-core
    versions:
    - 8.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
  - dependency-name: "@octokit/rest"
    versions:
    - 18.3.4
