image:
    file: .gitpod/dev.dockerfile

tasks:
    - init: |
          npm install
          npm run setup-full
      command: npm run watch
      name: Setup WebdriverIO Development Environment
    - init: |
        cd ./website
        npm install
      command: npm start
      name: Run Documentation Page

ports:
  - port: 3000
    onOpen: notify
    visibility: public

github:
    prebuilds:
        master: true
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: prevent-merge-on-error
        addComment: false
        addBadge: true
