os: linux
dist: xenial
language: node_js

cache:
  directories:
    - node_modules
    - packages

# e2e_setup: &e2e_setup
#   addons:
#     chrome: stable
#     firefox: latest-nightly
#   services:
#     - xvfb
#   script: npx run-s test:e2e

stages:
  - name: build
  - name: test
  - name: deploy

jobs:
  fast_finish: true
  include:
    - stage: build
      name: 'Build'
      script:
        - npx lerna bootstrap --no-ci
        - npx run-s build-full link
      node_js:
        - 10
        - 12
    - name: 'CI Tests (Node v10)'
      stage: test
      node_js: 10
      script:
        - npm run test
    - name: 'CI Tests (Node v12)'
      stage: test
      node_js: 12
      script:
        - npm run test
    # - <<: *base_setup
    #   <<: *e2e_setup
    #   name: 'e2e Tests (Linux)'
    # - <<: *base_setup
    #   <<: *e2e_setup
    #   name: 'e2e Tests (OSX)'
    #   os: osx
    # Windows on Travis is not stable enough yet
    # - <<: *base_setup
    #   <<: *e2e_setup
    #   name: 'e2e Tests (Windows)'
    #   os: windows
    - name: 'Release WebdriverIO Docs'
      script: skip
      stage: deploy
      node_js: 12
      deploy:
        provider: script
        script: "gem install compass && npm run docs"
        cleanup: true
        on:
          tags: true
